
trigger:
  - main

# Disable PR trigger as build validation is covered by GitHub Actions
pr: none

stages:

- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '24.x'
      displayName: 'Use Node 24'

    - script: |
        cd ./
        npm ci
        npm run build
      workingDirectory: '$(Build.SourcesDirectory)'
      displayName: 'npm install and build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'build'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/site.zip'
        replaceExistingArchive: true
      displayName: 'Archive build output'

    - publish: $(Build.ArtifactStagingDirectory)/site.zip
      artifact: drop


- stage: DeployTest
  displayName: 'Deploy test'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'Manual')))
  jobs:
  - deployment: Deploy
    environment: $(PIPELINES_ENVIRONMENT_TEST)
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(SERVICE_CONNECTION_TEST)' # pipeline variable
              appName: '$(APP_NAME_TEST)' # pipeline variable
              package: '$(Pipeline.Workspace)/drop/site.zip'
              startUpCommand: 'pm2 serve /home/site/wwwroot --no-daemon --spa'
            displayName: 'Deploy to Azure Web App'


- stage: DeployProd
  displayName: 'Deploy prod'
  dependsOn: DeployTest
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'Manual')))
  jobs:
  - deployment: DeployProd
    environment: $(PIPELINES_ENVIRONMENT_PROD)
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(SERVICE_CONNECTION_PROD)' # prod pipeline variable
              appName: '$(APP_NAME_PROD)' # prod pipeline variable
              package: '$(Pipeline.Workspace)/drop/site.zip'
              startUpCommand: 'pm2 serve /home/site/wwwroot --no-daemon --spa'
            displayName: 'Deploy to Azure Web App (Prod)'
